In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import warnings

# Mengabaikan peringatan SettingWithCopyWarning
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [2]:
df_jenisSampah = pd.read_excel("Data/Data_Komposisi_Jenis_Sampah_SIPSN_KLHK_Jawa Tengah.xlsx", header=1)
df_komposisiSampah = pd.read_excel("Data/Data_Komposisi_Sumber_Sampah_SIPSN_KLHK_Jawa Tengah.xlsx", header=1)
df_timbunanSampah = pd.read_excel("Data/Data_Timbulan_Sampah_SIPSN_KLHK_Jawa Tengah.xlsx", header=1)

In [3]:
df_jenisSampah.head(100)

,Tahun,Provinsi,Kabupaten/Kota,Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,2023,Jawa Tengah,Kab. Cilacap,57.67,1.71,9.71,16.42,1.33,1.25,NaN,1.17,10.74
1,2023,Jawa Tengah,Kab. Banyumas,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
2,2023,Jawa Tengah,Kab. Purworejo,15.20,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
3,2023,Jawa Tengah,Kab. Wonosobo,45.00,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
4,2023,Jawa Tengah,Kab. Magelang,45.41,6.71,4.43,24.87,0.61,2.15,0.68,1.32,13.82
5,2023,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023,Jawa Tengah,Kab. Sukoharjo,60.80,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
7,2023,Jawa Tengah,Kab. Sragen,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
8,2023,Jawa Tengah,Kab. Grobogan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023,Jawa Tengah,Kab. Blora,20.00,40.00,10.00,17.00,5.00,2.00,3.00,2.50,0.50
10,2023,Jawa Tengah,Kab. Jepara,53.31,0.96,8.79,23.36,0.69,2.44,0.94,1.16,8.35
11,2023,Jawa Tengah,Kab. Semarang,61.56,11.58,4.25,18.53,0.27,0.18,NaN,0.38,3.25
12,2023,Jawa Tengah,Kab. Temanggung,31.33,17.62,6.68,18.27,7.41,1.96,2.02,2.06,12.65
13,2023,Jawa Tengah,Kab. Pemalang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2023,Jawa Tengah,Kab. Tegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2023,Jawa Tengah,Kab. Brebes,5.00,50.00,5.00,25.00,4.00,4.00,1.00,1.00,5.00
16,2023,Jawa Tengah,Kota Magelang,33.70,13.30,18.80,21.50,0.80,1.80,0.50,3.70,5.90
17,2023,Jawa Tengah,Kota Salatiga,NaN,NaN,24.60,5.54,12.30,6.16,NaN,12.91,20.72
18,2023,Jawa Tengah,Kota Semarang,60.80,NaN,10.20,17.20,1.20,4.90,1.00,1.80,2.90
19,2022,Jawa Tengah,Kab. Banyumas,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
20,2022,Jawa Tengah,Kab. Kebumen,18.03,6.11,15.56,30.39,4.17,3.11,2.39,3.61,16.63
21,2022,Jawa Tengah,Kab. Purworejo,16.00,52.00,2.00,15.00,1.00,1.50,0.20,1.50,10.00
22,2022,Jawa Tengah,Kab. Wonosobo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2022,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2022,Jawa Tengah,Kab. Sukoharjo,63.40,1.98,9.91,16.13,1.78,1.28,1.12,1.27,3.13
25,2022,Jawa Tengah,Kab. Wonogiri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022,Jawa Tengah,Kab. Karanganyar,63.00,2.00,5.00,20.00,1.00,2.00,2.00,3.00,2.00
27,2022,Jawa Tengah,Kab. Sragen,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
28,2022,Jawa Tengah,Kab. Grobogan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2022,Jawa Tengah,Kab. Blora,22.00,6.00,15.00,42.00,8.00,2.00,1.50,3.00,0.50
30,2022,Jawa Tengah,Kab. Rembang,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
31,2022,Jawa Tengah,Kab. Pati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2022,Jawa Tengah,Kab. Kudus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2022,Jawa Tengah,Kab. Jepara,53.31,0.96,8.79,23.36,0.69,2.44,0.94,1.16,8.35
34,2022,Jawa Tengah,Kab. Tegal,41.00,13.00,11.00,16.00,7.00,3.00,3.00,1.00,5.00
35,2022,Jawa Tengah,Kota Salatiga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2022,Jawa Tengah,Kota Semarang,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88
37,2021,Jawa Tengah,Kab. Wonosobo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2021,Jawa Tengah,Kab. Magelang,37.80,3.90,26.20,17.90,1.30,1.10,0.80,2.40,8.60
39,2021,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2021,Jawa Tengah,Kab. Blora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2021,Jawa Tengah,Kab. Rembang,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
42,2021,Jawa Tengah,Kab. Kudus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2021,Jawa Tengah,Kab. Jepara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2021,Jawa Tengah,Kab. Semarang,13.00,12.00,12.00,25.00,7.00,8.00,6.00,5.00,12.00
45,2021,Jawa Tengah,Kab. Temanggung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2021,Jawa Tengah,Kab. Batang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2021,Jawa Tengah,Kab. Tegal,26.63,15.83,17.60,30.25,2.40,1.93,1.55,1.06,2.75
48,2020,Jawa Tengah,Kab. Kebumen,58.00,NaN,11.00,13.00,13.00,1.00,NaN,2.00,2.00
49,2020,Jawa Tengah,Kab. Purworejo,3.00,67.00,6.00,9.00,4.00,0.50,0.30,1.00,8.20
50,2020,Jawa Tengah,Kab. Wonosobo,40.00,21.45,10.00,20.00,0.20,0.20,0.15,1.00,2.00
51,2020,Jawa Tengah,Kab. Boyolali,53.84,1.80,13.31,20.89,1.10,1.57,1.05,0.98,5.46
52,2020,Jawa Tengah,Kab. Klaten,60.00,5.00,5.00,20.00,0.50,5.00,3.00,0.50,1.00
53,2020,Jawa Tengah,Kab. Wonogiri,22.30,29.48,19.74,11.81,6.54,NaN,NaN,6.07,4.06
54,2020,Jawa Tengah,Kab. Sragen,74.70,0.80,8.40,11.30,0.50,1.90,0.30,1.80,0.30
55,2020,Jawa Tengah,Kab. Rembang,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
56,2020,Jawa Tengah,Kab. Jepara,55.08,5.29,11.48,19.63,1.26,2.12,1.02,1.20,2.92
57,2020,Jawa Tengah,Kab. Temanggung,28.32,33.98,11.40,10.57,1.37,2.40,1.24,2.25,8.38
58,2020,Jawa Tengah,Kota Magelang,33.70,13.30,18.80,21.50,0.80,1.80,0.50,3.70,5.90
59,2020,Jawa Tengah,Kota Semarang,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88

In [4]:
df_jenisSampah.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tahun              60 non-null     int64
 1   Provinsi           60 non-null     object
 2   Kabupaten/Kota     60 non-null     object
 3   Sisa Makanan (%)   41 non-null     float64
 4   Kayu-Ranting (%)   37 non-null     float64
 5   Kertas-Karton (%)  42 non-null     float64
 6   Plastik(%)         42 non-null     float64
 7   Logam(%)           42 non-null     float64
 8   Kain(%)            41 non-null     float64
 9   Karet- Kulit (%)   37 non-null     float64
 10  Kaca(%)            42 non-null     float64
 11  Lainnya(%)         40 non-null     float64
dtypes: float64(9), int64(1), object(2)
memory usage: 5.8+ KB

In [5]:
df_jenisSampah.describe().T

,count,mean,std,min,25%,50%,75%,max
Tahun,60.0,2021.733333,1.117908,2020.00,2021.0000,2022.00,2023.0000,2023.00
Sisa Makanan (%),41.0,42.181220,19.396565,3.00,28.3200,40.00,60.0000,74.70
Kayu-Ranting (%),37.0,13.881351,17.569243,0.80,1.8000,6.00,15.8300,67.00
Kertas-Karton (%),42.0,10.763333,5.411076,2.00,7.1100,10.00,13.3625,26.20
Plastik(%),42.0,20.190476,7.910080,5.54,15.2500,18.40,24.4925,42.00
Logam(%),42.0,3.038810,3.395356,0.20,0.8325,1.24,4.1275,13.00
Kain(%),41.0,2.621707,1.723064,0.18,1.8000,2.00,3.1100,8.00
Karet- Kulit (%),37.0,1.541351,1.610468,0.10,0.6800,1.00,2.0000,8.00
Kaca(%),42.0,2.389048,2.171634,0.38,1.1775,1.79,2.8750,12.91
Lainnya(%),40.0,5.993750,4.780147,0.30,2.8475,5.00,8.3575,20.72

In [6]:
df_komposisiSampah.head(100)

,Tahun,Provinsi,Kabupaten/Kota,Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),Kawasan(ton),Lain(ton)
0,2023,Jawa Tengah,Kab. Cilacap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,Jawa Tengah,Kab. Banyumas,99999.99,16242.00,35733.00,68218.00,19491.00,12994.00,9747.00
2,2023,Jawa Tengah,Kab. Purworejo,22.20,0.01,27.60,NaN,0.80,3.60,11.40
3,2023,Jawa Tengah,Kab. Wonosobo,50.00,5.00,20.00,10.00,10.00,3.00,2.00
4,2023,Jawa Tengah,Kab. Magelang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2023,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023,Jawa Tengah,Kab. Sukoharjo,174.38,32.70,50.86,43.59,18.16,29.06,14.53
7,2023,Jawa Tengah,Kab. Sragen,187.36,40.01,148.00,49.89,102.40,63.94,3.75
8,2023,Jawa Tengah,Kab. Grobogan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023,Jawa Tengah,Kab. Blora,205.74,5.00,100.00,30.00,15.00,20.00,10.00
10,2023,Jawa Tengah,Kab. Jepara,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2023,Jawa Tengah,Kab. Semarang,144.00,NaN,52.00,NaN,NaN,24.00,1.00
12,2023,Jawa Tengah,Kab. Temanggung,275.12,12.79,12.11,10.42,50.51,NaN,42.77
13,2023,Jawa Tengah,Kab. Pemalang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2023,Jawa Tengah,Kab. Tegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2023,Jawa Tengah,Kab. Brebes,25.00,3.00,45.00,2.00,10.00,9.00,6.00
16,2023,Jawa Tengah,Kota Magelang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2023,Jawa Tengah,Kota Salatiga,NaN,NaN,NaN,NaN,NaN,NaN,0.75
18,2023,Jawa Tengah,Kota Semarang,72.00,0.50,2.60,8.00,9.00,6.60,1.30
19,2022,Jawa Tengah,Kab. Banyumas,99999.99,16242.00,35733.00,68218.00,19491.00,12994.00,9747.00
20,2022,Jawa Tengah,Kab. Kebumen,37.70,5.20,14.00,7.30,2.80,2.00,4.00
21,2022,Jawa Tengah,Kab. Purworejo,16.00,0.02,26.80,NaN,1.10,2.20,11.80
22,2022,Jawa Tengah,Kab. Wonosobo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2022,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2022,Jawa Tengah,Kab. Sukoharjo,152.71,25.32,61.23,43.17,21.59,50.37,5.37
25,2022,Jawa Tengah,Kab. Wonogiri,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022,Jawa Tengah,Kab. Karanganyar,60.00,2.00,27.72,2.00,2.00,1.00,1.00
27,2022,Jawa Tengah,Kab. Sragen,134.55,45.60,123.71,24.20,189.17,68.70,4.25
28,2022,Jawa Tengah,Kab. Grobogan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2022,Jawa Tengah,Kab. Blora,155.00,39.00,78.00,43.00,39.00,23.00,12.00
30,2022,Jawa Tengah,Kab. Rembang,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
31,2022,Jawa Tengah,Kab. Pati,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2022,Jawa Tengah,Kab. Kudus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2022,Jawa Tengah,Kab. Jepara,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2022,Jawa Tengah,Kab. Tegal,45.00,8.00,17.00,18.00,6.00,4.00,2.00
35,2022,Jawa Tengah,Kota Salatiga,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2022,Jawa Tengah,Kota Semarang,872.47,5.84,31.30,97.25,109.57,80.35,15.12
37,2021,Jawa Tengah,Kab. Wonosobo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2021,Jawa Tengah,Kab. Magelang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2021,Jawa Tengah,Kab. Boyolali,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2021,Jawa Tengah,Kab. Blora,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2021,Jawa Tengah,Kab. Rembang,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
42,2021,Jawa Tengah,Kab. Kudus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2021,Jawa Tengah,Kab. Jepara,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2021,Jawa Tengah,Kab. Semarang,20.00,10.00,25.00,10.00,10.00,15.00,10.00
45,2021,Jawa Tengah,Kab. Temanggung,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2021,Jawa Tengah,Kab. Batang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2021,Jawa Tengah,Kab. Tegal,239.25,2.56,108.80,105.59,43.66,216.26,420.68
48,2020,Jawa Tengah,Kab. Kebumen,40.00,7.00,4.00,3.00,8.00,3.00,4.00
49,2020,Jawa Tengah,Kab. Purworejo,93.92,0.02,0.34,0.02,0.58,NaN,NaN
50,2020,Jawa Tengah,Kab. Wonosobo,99999.99,0.70,29.00,7.60,12.40,NaN,NaN
51,2020,Jawa Tengah,Kab. Boyolali,284.70,NaN,NaN,NaN,NaN,NaN,NaN
52,2020,Jawa Tengah,Kab. Klaten,353.55,2.75,2.04,1.40,2.40,6.40,NaN
53,2020,Jawa Tengah,Kab. Wonogiri,74551.10,NaN,5095.20,NaN,NaN,NaN,NaN
54,2020,Jawa Tengah,Kab. Sragen,127.90,43.60,121.30,28.30,5.20,57.69,3.24
55,2020,Jawa Tengah,Kab. Rembang,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
56,2020,Jawa Tengah,Kab. Jepara,89046.41,20353.46,63604.58,25441.83,33074.38,12720.92,10176.73
57,2020,Jawa Tengah,Kab. Temanggung,55.00,4.00,15.43,6.00,10.00,9.00,11.00
58,2020,Jawa Tengah,Kota Magelang,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2020,Jawa Tengah,Kota Semarang,361.96,7.50,321.78,15.60,66.03,84.28,388.84

In [7]:
df_komposisiSampah.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tahun                  60 non-null     int64
 1   Provinsi               60 non-null     object
 2   Kabupaten/Kota         60 non-null     object
 3   Rumah Tangga(ton)      34 non-null     float64
 4   Perkantoran(ton)       31 non-null     float64
 5   Pasar(ton)             33 non-null     float64
 6   Perniagaan(ton)        29 non-null     float64
 7   Fasilitas Publik(ton)  31 non-null     float64
 8   Kawasan(ton)           26 non-null     float64
 9   Lain(ton)              30 non-null     float64
dtypes: float64(7), int64(1), object(2)
memory usage: 4.8+ KB

In [8]:
df_komposisiSampah.describe().T

,count,mean,std,min,25%,50%,75%,max
Tahun,60.0,2021.733333,1.117908,2020.00,2021.0000,2022.000,2023.0000,2023.00
Rumah Tangga(ton),34.0,13763.524412,33506.140024,16.00,52.2800,139.275,282.3050,99999.99
Perkantoran(ton),31.0,1714.729677,5325.187537,0.01,2.8750,5.200,29.0100,20353.46
Pasar(ton),33.0,4442.881515,13672.833765,0.34,20.0000,50.860,148.0000,63604.58
Perniagaan(ton),29.0,5601.524828,17972.970312,0.02,3.0000,10.420,43.1700,68218.00
Fasilitas Publik(ton),31.0,2363.153226,7484.947597,0.58,7.0000,15.000,105.9850,33074.38
Kawasan(ton),26.0,1518.898846,4193.348829,1.00,4.6000,21.500,67.5100,12994.00
Lain(ton),30.0,1023.103667,3008.627613,0.75,3.8125,10.500,13.8975,10176.73

In [9]:
df_timbunanSampah.head(100)

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton)
0,2023,Jawa Tengah,Kab. Cilacap,473.35,172771.48
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88
4,2023,Jawa Tengah,Kab. Magelang,615.28,224575.92
5,2023,Jawa Tengah,Kab. Boyolali,295.73,107941.52
6,2023,Jawa Tengah,Kab. Sukoharjo,363.29,132601.14
7,2023,Jawa Tengah,Kab. Sragen,595.35,217301.22
8,2023,Jawa Tengah,Kab. Grobogan,855.65,312313.22
9,2023,Jawa Tengah,Kab. Blora,387.49,141433.02
10,2023,Jawa Tengah,Kab. Jepara,408.81,149214.49
11,2023,Jawa Tengah,Kab. Semarang,533.16,194601.94
12,2023,Jawa Tengah,Kab. Temanggung,403.72,147357.80
13,2023,Jawa Tengah,Kab. Pemalang,600.30,219110.08
14,2023,Jawa Tengah,Kab. Tegal,705.29,257431.63
15,2023,Jawa Tengah,Kab. Brebes,1005.31,366937.60
16,2023,Jawa Tengah,Kota Magelang,80.55,29400.33
17,2023,Jawa Tengah,Kota Salatiga,116.13,42386.57
18,2023,Jawa Tengah,Kota Semarang,1182.29,431534.65
19,2022,Jawa Tengah,Kab. Banyumas,535.23,195357.75
20,2022,Jawa Tengah,Kab. Kebumen,463.05,169013.40
21,2022,Jawa Tengah,Kab. Purworejo,289.57,105694.22
22,2022,Jawa Tengah,Kab. Wonosobo,364.63,133089.95
23,2022,Jawa Tengah,Kab. Boyolali,291.48,106389.55
24,2022,Jawa Tengah,Kab. Sukoharjo,359.76,131313.42
25,2022,Jawa Tengah,Kab. Wonogiri,347.72,126917.85
26,2022,Jawa Tengah,Kab. Karanganyar,375.52,137065.97
27,2022,Jawa Tengah,Kab. Sragen,590.18,215417.38
28,2022,Jawa Tengah,Kab. Grobogan,838.53,306061.73
29,2022,Jawa Tengah,Kab. Blora,383.05,139811.75
30,2022,Jawa Tengah,Kab. Rembang,252.63,92209.49
31,2022,Jawa Tengah,Kab. Pati,674.59,246223.89
32,2022,Jawa Tengah,Kab. Kudus,448.16,163578.95
33,2022,Jawa Tengah,Kab. Jepara,400.05,146019.25
34,2022,Jawa Tengah,Kab. Tegal,690.73,252115.34
35,2022,Jawa Tengah,Kota Salatiga,112.24,40969.24
36,2022,Jawa Tengah,Kota Semarang,1181.06,431085.22
37,2021,Jawa Tengah,Kab. Wonosobo,363.00,132496.46
38,2021,Jawa Tengah,Kab. Magelang,681.65,248800.43
39,2021,Jawa Tengah,Kab. Boyolali,290.85,106159.34
40,2021,Jawa Tengah,Kab. Blora,380.26,138796.06
41,2021,Jawa Tengah,Kab. Rembang,244.53,89254.42
42,2021,Jawa Tengah,Kab. Kudus,445.93,162765.18
43,2021,Jawa Tengah,Kab. Jepara,704.09,256992.72
44,2021,Jawa Tengah,Kab. Semarang,521.41,190314.00
45,2021,Jawa Tengah,Kab. Temanggung,500.17,182562.96
46,2021,Jawa Tengah,Kab. Batang,245.33,89543.84
47,2021,Jawa Tengah,Kab. Tegal,1117.90,408032.48
48,2020,Jawa Tengah,Kab. Kebumen,407.80,148846.66
49,2020,Jawa Tengah,Kab. Purworejo,288.07,105146.86
50,2020,Jawa Tengah,Kab. Wonosobo,317.37,115840.34
51,2020,Jawa Tengah,Kab. Boyolali,284.68,103907.38
52,2020,Jawa Tengah,Kab. Klaten,353.55,129045.86
53,2020,Jawa Tengah,Kab. Wonogiri,437.62,159730.28
54,2020,Jawa Tengah,Kab. Sragen,534.31,195023.44
55,2020,Jawa Tengah,Kab. Rembang,237.41,86654.43
56,2020,Jawa Tengah,Kab. Jepara,697.04,254418.30
57,2020,Jawa Tengah,Kab. Temanggung,496.28,181143.80
58,2020,Jawa Tengah,Kota Magelang,85.48,31199.36
59,2020,Jawa Tengah,Kota Semarang,1276.74,466010.79

In [10]:
df_timbunanSampah.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Tahun                         60 non-null     int64
 1   Provinsi                      60 non-null     object
 2   Kabupaten/Kota                60 non-null     object
 3   Timbulan Sampah Harian(ton)   60 non-null     float64
 4   Timbulan Sampah Tahunan(ton)  60 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.5+ KB

In [11]:
df_timbunanSampah.describe().T

,count,mean,std,min,25%,50%,75%,max
Tahun,60.0,2021.733333,1.117908,2020.00,2021.0000,2022.000,2023.0000,2023.00
Timbulan Sampah Harian(ton),60.0,489.447500,265.173871,80.55,320.6400,408.305,596.5875,1276.74
Timbulan Sampah Tahunan(ton),60.0,178648.192667,96788.225833,29400.33,117034.7675,149030.575,217753.4350,466010.79

In [12]:
df_jenisSampah.columns

Index(['Tahun', 'Provinsi', 'Kabupaten/Kota', 'Sisa Makanan (%)',
       'Kayu-Ranting (%)', 'Kertas-Karton (%)', 'Plastik(%)', 'Logam(%)',
       'Kain(%)', 'Karet- Kulit (%)', 'Kaca(%)', 'Lainnya(%)'],
      dtype='object')

In [13]:
df_komposisiSampah.columns

Index(['Tahun', 'Provinsi', 'Kabupaten/Kota', 'Rumah Tangga(ton)',
       'Perkantoran(ton)', 'Pasar(ton)', 'Perniagaan(ton)',
       'Fasilitas Publik(ton)', 'Kawasan(ton)', 'Lain(ton)'],
      dtype='object')

In [14]:
df_timbunanSampah.columns

Index(['Tahun', 'Provinsi', 'Kabupaten/Kota', 'Timbulan Sampah Harian(ton)',
       'Timbulan Sampah Tahunan(ton)'],
      dtype='object')

In [15]:
df = df_timbunanSampah
df.head()

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton)
0,2023,Jawa Tengah,Kab. Cilacap,473.35,172771.48
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88
4,2023,Jawa Tengah,Kab. Magelang,615.28,224575.92

In [16]:
cols1 = ['Rumah Tangga(ton)',
       'Perkantoran(ton)', 'Pasar(ton)', 'Perniagaan(ton)',
       'Fasilitas Publik(ton)', 'Kawasan(ton)', 'Lain(ton)']

for col in cols1:
    df[col] = df_komposisiSampah[col]

In [17]:
df.head()

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton),Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),Kawasan(ton),Lain(ton)
0,2023,Jawa Tengah,Kab. Cilacap,473.35,172771.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42,99999.99,16242.00,35733.0,68218.0,19491.0,12994.0,9747.0
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91,22.20,0.01,27.6,NaN,0.8,3.6,11.4
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88,50.00,5.00,20.0,10.0,10.0,3.0,2.0
4,2023,Jawa Tengah,Kab. Magelang,615.28,224575.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
cols2 = ['Sisa Makanan (%)',
       'Kayu-Ranting (%)', 'Kertas-Karton (%)', 'Plastik(%)', 'Logam(%)',
       'Kain(%)', 'Karet- Kulit (%)', 'Kaca(%)', 'Lainnya(%)']

for col in cols2:
    df[col] = df_jenisSampah[col]

In [19]:
df.head(100)

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton),Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),...,Lain(ton),Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,2023,Jawa Tengah,Kab. Cilacap,473.35,172771.48,NaN,NaN,NaN,NaN,NaN,...,NaN,57.67,1.71,9.71,16.42,1.33,1.25,NaN,1.17,10.74
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42,99999.99,16242.00,35733.00,68218.00,19491.00,...,9747.00,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91,22.20,0.01,27.60,NaN,0.80,...,11.40,15.20,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88,50.00,5.00,20.00,10.00,10.00,...,2.00,45.00,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
4,2023,Jawa Tengah,Kab. Magelang,615.28,224575.92,NaN,NaN,NaN,NaN,NaN,...,NaN,45.41,6.71,4.43,24.87,0.61,2.15,0.68,1.32,13.82
5,2023,Jawa Tengah,Kab. Boyolali,295.73,107941.52,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023,Jawa Tengah,Kab. Sukoharjo,363.29,132601.14,174.38,32.70,50.86,43.59,18.16,...,14.53,60.80,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
7,2023,Jawa Tengah,Kab. Sragen,595.35,217301.22,187.36,40.01,148.00,49.89,102.40,...,3.75,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
8,2023,Jawa Tengah,Kab. Grobogan,855.65,312313.22,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023,Jawa Tengah,Kab. Blora,387.49,141433.02,205.74,5.00,100.00,30.00,15.00,...,10.00,20.00,40.00,10.00,17.00,5.00,2.00,3.00,2.50,0.50
10,2023,Jawa Tengah,Kab. Jepara,408.81,149214.49,NaN,NaN,NaN,NaN,NaN,...,NaN,53.31,0.96,8.79,23.36,0.69,2.44,0.94,1.16,8.35
11,2023,Jawa Tengah,Kab. Semarang,533.16,194601.94,144.00,NaN,52.00,NaN,NaN,...,1.00,61.56,11.58,4.25,18.53,0.27,0.18,NaN,0.38,3.25
12,2023,Jawa Tengah,Kab. Temanggung,403.72,147357.80,275.12,12.79,12.11,10.42,50.51,...,42.77,31.33,17.62,6.68,18.27,7.41,1.96,2.02,2.06,12.65
13,2023,Jawa Tengah,Kab. Pemalang,600.30,219110.08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2023,Jawa Tengah,Kab. Tegal,705.29,257431.63,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2023,Jawa Tengah,Kab. Brebes,1005.31,366937.60,25.00,3.00,45.00,2.00,10.00,...,6.00,5.00,50.00,5.00,25.00,4.00,4.00,1.00,1.00,5.00
16,2023,Jawa Tengah,Kota Magelang,80.55,29400.33,NaN,NaN,NaN,NaN,NaN,...,NaN,33.70,13.30,18.80,21.50,0.80,1.80,0.50,3.70,5.90
17,2023,Jawa Tengah,Kota Salatiga,116.13,42386.57,NaN,NaN,NaN,NaN,NaN,...,0.75,NaN,NaN,24.60,5.54,12.30,6.16,NaN,12.91,20.72
18,2023,Jawa Tengah,Kota Semarang,1182.29,431534.65,72.00,0.50,2.60,8.00,9.00,...,1.30,60.80,NaN,10.20,17.20,1.20,4.90,1.00,1.80,2.90
19,2022,Jawa Tengah,Kab. Banyumas,535.23,195357.75,99999.99,16242.00,35733.00,68218.00,19491.00,...,9747.00,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
20,2022,Jawa Tengah,Kab. Kebumen,463.05,169013.40,37.70,5.20,14.00,7.30,2.80,...,4.00,18.03,6.11,15.56,30.39,4.17,3.11,2.39,3.61,16.63
21,2022,Jawa Tengah,Kab. Purworejo,289.57,105694.22,16.00,0.02,26.80,NaN,1.10,...,11.80,16.00,52.00,2.00,15.00,1.00,1.50,0.20,1.50,10.00
22,2022,Jawa Tengah,Kab. Wonosobo,364.63,133089.95,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2022,Jawa Tengah,Kab. Boyolali,291.48,106389.55,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2022,Jawa Tengah,Kab. Sukoharjo,359.76,131313.42,152.71,25.32,61.23,43.17,21.59,...,5.37,63.40,1.98,9.91,16.13,1.78,1.28,1.12,1.27,3.13
25,2022,Jawa Tengah,Kab. Wonogiri,347.72,126917.85,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022,Jawa Tengah,Kab. Karanganyar,375.52,137065.97,60.00,2.00,27.72,2.00,2.00,...,1.00,63.00,2.00,5.00,20.00,1.00,2.00,2.00,3.00,2.00
27,2022,Jawa Tengah,Kab. Sragen,590.18,215417.38,134.55,45.60,123.71,24.20,189.17,...,4.25,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
28,2022,Jawa Tengah,Kab. Grobogan,838.53,306061.73,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2022,Jawa Tengah,Kab. Blora,383.05,139811.75,155.00,39.00,78.00,43.00,39.00,...,12.00,22.00,6.00,15.00,42.00,8.00,2.00,1.50,3.00,0.50
30,2022,Jawa Tengah,Kab. Rembang,252.63,92209.49,52.28,3.68,1661.23,0.02,152.00,...,11.86,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
31,2022,Jawa Tengah,Kab. Pati,674.59,246223.89,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2022,Jawa Tengah,Kab. Kudus,448.16,163578.95,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2022,Jawa Tengah,Kab. Jepara,400.05,146019.25,NaN,NaN,NaN,NaN,NaN,...,NaN,53.31,0.96,8.79,23.36,0.69,2.44,0.94,1.16,8.35
34,2022,Jawa Tengah,Kab. Tegal,690.73,252115.34,45.00,8.00,17.00,18.00,6.00,...,2.00,41.00,13.00,11.00,16.00,7.00,3.00,3.00,1.00,5.00
35,2022,Jawa Tengah,Kota Salatiga,112.24,40969.24,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2022,Jawa Tengah,Kota Semarang,1181.06,431085.22,872.47,5.84,31.30,97.25,109.57,...,15.12,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88
37,2021,Jawa Tengah,Kab. Wonosobo,363.00,132496.46,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2021,Jawa Tengah,Kab. Magelang,681.65,248800.43,NaN,NaN,NaN,NaN,NaN,...,NaN,37.80,3.90,26.20,17.90,1.30,1.10,0.80,2.40,8.60
39,2021,Jawa Tengah,Kab. Boyolali,290.85,106159.34,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2021,Jawa Tengah,Kab. Blora,380.26,138796.06,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2021,Jawa Tengah,Kab. Rembang,244.53,89254.42,52.28,3.68,1661.23,0.02,152.00,...,11.86,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
42,2021,Jawa Tengah,Kab. Kudus,445.93,162765.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2021,Jawa Tengah,Kab. Jepara,704.09,256992.72,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2021,Jawa Tengah,Kab. Semarang,521.41,190314.00,20.00,10.00,25.00,10.00,10.00,...,10.00,13.00,12.00,12.00,25.00,7.00,8.00,6.00,5.00,12.00
45,2021,Jawa Tengah,Kab. Temanggung,500.17,182562.96,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2021,Jawa Tengah,Kab. Batang,245.33,89543.84,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2021,Jawa Tengah,Kab. Tegal,1117.90,408032.48,239.25,2.56,108.80,105.59,43.66,...,420.68,26.63,15.83,17.60,30.25,2.40,1.93,1.55,1.06,2.75
48,2020,Jawa Tengah,Kab. Kebumen,407.80,148846.66,40.00,7.00,4.00,3.00,8.00,...,4.00,58.00,NaN,11.00,13.00,13.00,1.00,NaN,2.00,2.00
49,2020,Jawa Tengah,Kab. Purworejo,288.07,105146.86,93.92,0.02,0.34,0.02,0.58,...,NaN,3.00,67.00,6.00,9.00,4.00,0.50,0.30,1.00,8.20
50,2020,Jawa Tengah,Kab. Wonosobo,317.37,115840.34,99999.99,0.70,29.00,7.60,12.40,...,NaN,40.00,21.45,10.00,20.00,0.20,0.20,0.15,1.00,2.00
51,2020,Jawa Tengah,Kab. Boyolali,284.68,103907.38,284.70,NaN,NaN,NaN,NaN,...,NaN,53.84,1.80,13.31,20.89,1.10,1.57,1.05,0.98,5.46
52,2020,Jawa Tengah,Kab. Klaten,353.55,129045.86,353.55,2.75,2.04,1.40,2.40,...,NaN,60.00,5.00,5.00,20.00,0.50,5.00,3.00,0.50,1.00
53,2020,Jawa Tengah,Kab. Wonogiri,437.62,159730.28,74551.10,NaN,5095.20,NaN,NaN,...,NaN,22.30,29.48,19.74,11.81,6.54,NaN,NaN,6.07,4.06
54,2020,Jawa Tengah,Kab. Sragen,534.31,195023.44,127.90,43.60,121.30,28.30,5.20,...,3.24,74.70,0.80,8.40,11.30,0.50,1.90,0.30,1.80,0.30
55,2020,Jawa Tengah,Kab. Rembang,237.41,86654.43,52.28,3.68,1661.23,0.02,152.00,...,11.86,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
56,2020,Jawa Tengah,Kab. Jepara,697.04,254418.30,89046.41,20353.46,63604.58,25441.83,33074.38,...,10176.73,55.08,5.29,11.48,19.63,1.26,2.12,1.02,1.20,2.92
57,2020,Jawa Tengah,Kab. Temanggung,496.28,181143.80,55.00,4.00,15.43,6.00,10.00,...,11.00,28.32,33.98,11.40,10.57,1.37,2.40,1.24,2.25,8.38
58,2020,Jawa Tengah,Kota Magelang,85.48,31199.36,NaN,NaN,NaN,NaN,NaN,...,NaN,33.70,13.30,18.80,21.50,0.80,1.80,0.50,3.70,5.90
59,2020,Jawa Tengah,Kota Semarang,1276.74,466010.79,361.96,7.50,321.78,15.60,66.03,...,388.84,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Tahun                         60 non-null     int64
 1   Provinsi                      60 non-null     object
 2   Kabupaten/Kota                60 non-null     object
 3   Timbulan Sampah Harian(ton)   60 non-null     float64
 4   Timbulan Sampah Tahunan(ton)  60 non-null     float64
 5   Rumah Tangga(ton)             34 non-null     float64
 6   Perkantoran(ton)              31 non-null     float64
 7   Pasar(ton)                    33 non-null     float64
 8   Perniagaan(ton)               29 non-null     float64
 9   Fasilitas Publik(ton)         31 non-null     float64
 10  Kawasan(ton)                  26 non-null     float64
 11  Lain(ton)                     30 non-null     float64
 12  Sisa Makanan (%)              41 non-null     float64
 13  Kayu-Ranting (%)              37 non-null     float64
 14  Kertas-Karton (%)             42 non-null     float64
 15  Plastik(%)                    42 non-null     float64
 16  Logam(%)                      42 non-null     float64
 17  Kain(%)                       41 non-null     float64
 18  Karet- Kulit (%)              37 non-null     float64
 19  Kaca(%)                       42 non-null     float64
 20  Lainnya(%)                    40 non-null     float64
dtypes: float64(18), int64(1), object(2)
memory usage: 10.0+ KB

In [21]:
df.dropna(subset=cols1, how="all", axis=0, inplace=True)
df.head()

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton),Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),...,Lain(ton),Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42,99999.99,16242.00,35733.00,68218.00,19491.00,...,9747.00,36.0,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91,22.20,0.01,27.60,NaN,0.80,...,11.40,15.2,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88,50.00,5.00,20.00,10.00,10.00,...,2.00,45.0,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
6,2023,Jawa Tengah,Kab. Sukoharjo,363.29,132601.14,174.38,32.70,50.86,43.59,18.16,...,14.53,60.8,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
7,2023,Jawa Tengah,Kab. Sragen,595.35,217301.22,187.36,40.01,148.00,49.89,102.40,...,3.75,74.3,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40

In [22]:
df.dropna(subset=cols2, how="all", axis=0, inplace=True)
df.head()

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton),Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),...,Lain(ton),Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
1,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42,99999.99,16242.00,35733.00,68218.00,19491.00,...,9747.00,36.0,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
2,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91,22.20,0.01,27.60,NaN,0.80,...,11.40,15.2,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
3,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88,50.00,5.00,20.00,10.00,10.00,...,2.00,45.0,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
6,2023,Jawa Tengah,Kab. Sukoharjo,363.29,132601.14,174.38,32.70,50.86,43.59,18.16,...,14.53,60.8,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
7,2023,Jawa Tengah,Kab. Sragen,595.35,217301.22,187.36,40.01,148.00,49.89,102.40,...,3.75,74.3,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 1 to 59
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Tahun                         35 non-null     int64
 1   Provinsi                      35 non-null     object
 2   Kabupaten/Kota                35 non-null     object
 3   Timbulan Sampah Harian(ton)   35 non-null     float64
 4   Timbulan Sampah Tahunan(ton)  35 non-null     float64
 5   Rumah Tangga(ton)             34 non-null     float64
 6   Perkantoran(ton)              31 non-null     float64
 7   Pasar(ton)                    33 non-null     float64
 8   Perniagaan(ton)               29 non-null     float64
 9   Fasilitas Publik(ton)         31 non-null     float64
 10  Kawasan(ton)                  26 non-null     float64
 11  Lain(ton)                     30 non-null     float64
 12  Sisa Makanan (%)              34 non-null     float64
 13  Kayu-Ranting (%)              30 non-null     float64
 14  Kertas-Karton (%)             35 non-null     float64
 15  Plastik(%)                    35 non-null     float64
 16  Logam(%)                      35 non-null     float64
 17  Kain(%)                       34 non-null     float64
 18  Karet- Kulit (%)              31 non-null     float64
 19  Kaca(%)                       35 non-null     float64
 20  Lainnya(%)                    33 non-null     float64
dtypes: float64(18), int64(1), object(2)
memory usage: 6.0+ KB

In [24]:
df.reset_index(drop=True, inplace=True)
df.head()

,Tahun,Provinsi,Kabupaten/Kota,Timbulan Sampah Harian(ton),Timbulan Sampah Tahunan(ton),Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),...,Lain(ton),Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,2023,Jawa Tengah,Kab. Banyumas,541.80,197758.42,99999.99,16242.00,35733.00,68218.00,19491.00,...,9747.00,36.0,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
1,2023,Jawa Tengah,Kab. Purworejo,321.73,117432.91,22.20,0.01,27.60,NaN,0.80,...,11.40,15.2,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
2,2023,Jawa Tengah,Kab. Wonosobo,371.97,135767.88,50.00,5.00,20.00,10.00,10.00,...,2.00,45.0,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
3,2023,Jawa Tengah,Kab. Sukoharjo,363.29,132601.14,174.38,32.70,50.86,43.59,18.16,...,14.53,60.8,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
4,2023,Jawa Tengah,Kab. Sragen,595.35,217301.22,187.36,40.01,148.00,49.89,102.40,...,3.75,74.3,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40

In [25]:
df[cols1]

,Rumah Tangga(ton),Perkantoran(ton),Pasar(ton),Perniagaan(ton),Fasilitas Publik(ton),Kawasan(ton),Lain(ton)
0,99999.99,16242.00,35733.00,68218.00,19491.00,12994.00,9747.00
1,22.20,0.01,27.60,NaN,0.80,3.60,11.40
2,50.00,5.00,20.00,10.00,10.00,3.00,2.00
3,174.38,32.70,50.86,43.59,18.16,29.06,14.53
4,187.36,40.01,148.00,49.89,102.40,63.94,3.75
5,205.74,5.00,100.00,30.00,15.00,20.00,10.00
6,144.00,NaN,52.00,NaN,NaN,24.00,1.00
7,275.12,12.79,12.11,10.42,50.51,NaN,42.77
8,25.00,3.00,45.00,2.00,10.00,9.00,6.00
9,NaN,NaN,NaN,NaN,NaN,NaN,0.75
10,72.00,0.50,2.60,8.00,9.00,6.60,1.30
11,99999.99,16242.00,35733.00,68218.00,19491.00,12994.00,9747.00
12,37.70,5.20,14.00,7.30,2.80,2.00,4.00
13,16.00,0.02,26.80,NaN,1.10,2.20,11.80
14,152.71,25.32,61.23,43.17,21.59,50.37,5.37
15,60.00,2.00,27.72,2.00,2.00,1.00,1.00
16,134.55,45.60,123.71,24.20,189.17,68.70,4.25
17,155.00,39.00,78.00,43.00,39.00,23.00,12.00
18,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
19,45.00,8.00,17.00,18.00,6.00,4.00,2.00
20,872.47,5.84,31.30,97.25,109.57,80.35,15.12
21,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
22,20.00,10.00,25.00,10.00,10.00,15.00,10.00
23,239.25,2.56,108.80,105.59,43.66,216.26,420.68
24,40.00,7.00,4.00,3.00,8.00,3.00,4.00
25,93.92,0.02,0.34,0.02,0.58,NaN,NaN
26,99999.99,0.70,29.00,7.60,12.40,NaN,NaN
27,284.70,NaN,NaN,NaN,NaN,NaN,NaN
28,353.55,2.75,2.04,1.40,2.40,6.40,NaN
29,74551.10,NaN,5095.20,NaN,NaN,NaN,NaN
30,127.90,43.60,121.30,28.30,5.20,57.69,3.24
31,52.28,3.68,1661.23,0.02,152.00,NaN,11.86
32,89046.41,20353.46,63604.58,25441.83,33074.38,12720.92,10176.73
33,55.00,4.00,15.43,6.00,10.00,9.00,11.00
34,361.96,7.50,321.78,15.60,66.03,84.28,388.84

In [26]:
df[cols2]

,Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
1,15.20,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
2,45.00,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
3,60.80,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
4,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
5,20.00,40.00,10.00,17.00,5.00,2.00,3.00,2.50,0.50
6,61.56,11.58,4.25,18.53,0.27,0.18,NaN,0.38,3.25
7,31.33,17.62,6.68,18.27,7.41,1.96,2.02,2.06,12.65
8,5.00,50.00,5.00,25.00,4.00,4.00,1.00,1.00,5.00
9,NaN,NaN,24.60,5.54,12.30,6.16,NaN,12.91,20.72
10,60.80,NaN,10.20,17.20,1.20,4.90,1.00,1.80,2.90
11,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
12,18.03,6.11,15.56,30.39,4.17,3.11,2.39,3.61,16.63
13,16.00,52.00,2.00,15.00,1.00,1.50,0.20,1.50,10.00
14,63.40,1.98,9.91,16.13,1.78,1.28,1.12,1.27,3.13
15,63.00,2.00,5.00,20.00,1.00,2.00,2.00,3.00,2.00
16,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
17,22.00,6.00,15.00,42.00,8.00,2.00,1.50,3.00,0.50
18,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
19,41.00,13.00,11.00,16.00,7.00,3.00,3.00,1.00,5.00
20,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88
21,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
22,13.00,12.00,12.00,25.00,7.00,8.00,6.00,5.00,12.00
23,26.63,15.83,17.60,30.25,2.40,1.93,1.55,1.06,2.75
24,58.00,NaN,11.00,13.00,13.00,1.00,NaN,2.00,2.00
25,3.00,67.00,6.00,9.00,4.00,0.50,0.30,1.00,8.20
26,40.00,21.45,10.00,20.00,0.20,0.20,0.15,1.00,2.00
27,53.84,1.80,13.31,20.89,1.10,1.57,1.05,0.98,5.46
28,60.00,5.00,5.00,20.00,0.50,5.00,3.00,0.50,1.00
29,22.30,29.48,19.74,11.81,6.54,NaN,NaN,6.07,4.06
30,74.70,0.80,8.40,11.30,0.50,1.90,0.30,1.80,0.30
31,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
32,55.08,5.29,11.48,19.63,1.26,2.12,1.02,1.20,2.92
33,28.32,33.98,11.40,10.57,1.37,2.40,1.24,2.25,8.38
34,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88

In [27]:
df_coba = df[cols2]
df_coba

,Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
1,15.20,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
2,45.00,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
3,60.80,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
4,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
5,20.00,40.00,10.00,17.00,5.00,2.00,3.00,2.50,0.50
6,61.56,11.58,4.25,18.53,0.27,0.18,NaN,0.38,3.25
7,31.33,17.62,6.68,18.27,7.41,1.96,2.02,2.06,12.65
8,5.00,50.00,5.00,25.00,4.00,4.00,1.00,1.00,5.00
9,NaN,NaN,24.60,5.54,12.30,6.16,NaN,12.91,20.72
10,60.80,NaN,10.20,17.20,1.20,4.90,1.00,1.80,2.90
11,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,NaN
12,18.03,6.11,15.56,30.39,4.17,3.11,2.39,3.61,16.63
13,16.00,52.00,2.00,15.00,1.00,1.50,0.20,1.50,10.00
14,63.40,1.98,9.91,16.13,1.78,1.28,1.12,1.27,3.13
15,63.00,2.00,5.00,20.00,1.00,2.00,2.00,3.00,2.00
16,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
17,22.00,6.00,15.00,42.00,8.00,2.00,1.50,3.00,0.50
18,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
19,41.00,13.00,11.00,16.00,7.00,3.00,3.00,1.00,5.00
20,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88
21,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
22,13.00,12.00,12.00,25.00,7.00,8.00,6.00,5.00,12.00
23,26.63,15.83,17.60,30.25,2.40,1.93,1.55,1.06,2.75
24,58.00,NaN,11.00,13.00,13.00,1.00,NaN,2.00,2.00
25,3.00,67.00,6.00,9.00,4.00,0.50,0.30,1.00,8.20
26,40.00,21.45,10.00,20.00,0.20,0.20,0.15,1.00,2.00
27,53.84,1.80,13.31,20.89,1.10,1.57,1.05,0.98,5.46
28,60.00,5.00,5.00,20.00,0.50,5.00,3.00,0.50,1.00
29,22.30,29.48,19.74,11.81,6.54,NaN,NaN,6.07,4.06
30,74.70,0.80,8.40,11.30,0.50,1.90,0.30,1.80,0.30
31,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
32,55.08,5.29,11.48,19.63,1.26,2.12,1.02,1.20,2.92
33,28.32,33.98,11.40,10.57,1.37,2.40,1.24,2.25,8.38
34,60.79,NaN,10.18,17.20,1.22,4.94,1.00,1.79,2.88

In [28]:
"""#cek kolom yang missing
misscol = []
for col in cols2:
    if pd.isnull(df_coba.loc[0, col]) == True:
        misscol.append(col)
sisacol = list(set(cols2) - set(misscol))
# jumlah
if len(misscol) == 1:
    total = df_coba.loc[0, sisacol].tolist()
    total = sum(total)
    total = 100-total
    df_coba.loc[0, misscol] = total
elif len(misscol)>1:
    total = df_coba.loc[0,sisacol].tolist()
    total = sum(total)
    total = (100-total)/len(misscol)
    for col in misscol:
        df_coba.loc[0, col] = total"""

'#cek kolom yang missing\nmisscol = []\nfor col in cols2:\n    if pd.isnull(df_coba.loc[0, col]) == True:\n        misscol.append(col)\nsisacol = list(set(cols2) - set(misscol))\n# jumlah\nif len(misscol) == 1:\n    total = df_coba.loc[0, sisacol].tolist()\n    total = sum(total)\n    total = 100-total\n    df_coba.loc[0, misscol] = total\nelif len(misscol)>1:\n    total = df_coba.loc[0,sisacol].tolist()\n    total = sum(total)\n    total = (100-total)/len(misscol)\n    for col in misscol:\n        df_coba.loc[0, col] = total'

In [29]:
misscol = []
for col in cols2:
    if pd.isnull(df_coba.loc[0, col]) == True:
        misscol.append(col)
sisacol = list(set(cols2) - set(misscol))

print("misscol", misscol)
print("sisacol", sisacol)

listval = total = df_coba.loc[0, sisacol].tolist()
print("lisval :", listval)
total = sum(listval)
print("Total1 :", total)
total = 100-total
print("Total1 :", total)
#df_coba.loc[0, misscol] = total

misscol ['Lainnya(%)']
sisacol ['Logam(%)', 'Kertas-Karton (%)', 'Kain(%)', 'Sisa Makanan (%)', 'Karet- Kulit (%)', 'Kayu-Ranting (%)', 'Kaca(%)', 'Plastik(%)']
lisval : [9.0, 6.0, 5.0, 36.0, 3.0, 6.0, 5.0, 30.0]
Total1 : 100.0
Total1 : 0.0

In [30]:
len(df_coba.index)

35

In [31]:
for i in range(len(df_coba.index)):
    misscol = []
    for col in cols2:
        if pd.isnull(df_coba.loc[i, col]) == True:
            misscol.append(col)
    sisacol = list(set(cols2) - set(misscol))
    if len(misscol)==1:
        listval = total = df_coba.loc[i, sisacol].tolist()
        total = sum(listval)
        total = 100-total
        df_coba.loc[i, misscol] = total
    elif len(misscol)>1:
        total = df_coba.loc[i,sisacol].tolist()
        total = sum(total)
        total = (100-total)/len(misscol)
        total = round(total,2)
        for col in misscol:
            df_coba.loc[i, misscol] = total

/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total
/var/folders/nd/s6snn9l53zg5sthh_ttcvdpr0000gn/T/ipykernel_73396/476055278.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coba.loc[i, misscol] = total

In [34]:
df_coba.head(100)

,Sisa Makanan (%),Kayu-Ranting (%),Kertas-Karton (%),Plastik(%),Logam(%),Kain(%),Karet- Kulit (%),Kaca(%),Lainnya(%)
0,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,0.00
1,15.20,52.60,2.30,14.40,1.20,1.40,0.10,1.40,11.40
2,45.00,7.00,9.00,15.00,3.00,5.00,8.00,5.00,3.00
3,60.80,1.88,9.81,17.03,1.98,2.28,1.82,1.27,3.13
4,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
5,20.00,40.00,10.00,17.00,5.00,2.00,3.00,2.50,0.50
6,61.56,11.58,4.25,18.53,0.27,0.18,0.00,0.38,3.25
7,31.33,17.62,6.68,18.27,7.41,1.96,2.02,2.06,12.65
8,5.00,50.00,5.00,25.00,4.00,4.00,1.00,1.00,5.00
9,5.92,5.92,24.60,5.54,12.30,6.16,5.92,12.91,20.72
10,60.80,0.00,10.20,17.20,1.20,4.90,1.00,1.80,2.90
11,36.00,6.00,6.00,30.00,9.00,5.00,3.00,5.00,0.00
12,18.03,6.11,15.56,30.39,4.17,3.11,2.39,3.61,16.63
13,16.00,52.00,2.00,15.00,1.00,1.50,0.20,1.50,10.00
14,63.40,1.98,9.91,16.13,1.78,1.28,1.12,1.27,3.13
15,63.00,2.00,5.00,20.00,1.00,2.00,2.00,3.00,2.00
16,74.30,0.80,8.90,11.20,0.50,1.80,0.30,1.80,0.40
17,22.00,6.00,15.00,42.00,8.00,2.00,1.50,3.00,0.50
18,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
19,41.00,13.00,11.00,16.00,7.00,3.00,3.00,1.00,5.00
20,60.79,0.00,10.18,17.20,1.22,4.94,1.00,1.79,2.88
21,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
22,13.00,12.00,12.00,25.00,7.00,8.00,6.00,5.00,12.00
23,26.63,15.83,17.60,30.25,2.40,1.93,1.55,1.06,2.75
24,58.00,0.00,11.00,13.00,13.00,1.00,0.00,2.00,2.00
25,3.00,67.00,6.00,9.00,4.00,0.50,0.30,1.00,8.20
26,40.00,21.45,10.00,20.00,0.20,0.20,0.15,1.00,2.00
27,53.84,1.80,13.31,20.89,1.10,1.57,1.05,0.98,5.46
28,60.00,5.00,5.00,20.00,0.50,5.00,3.00,0.50,1.00
29,22.30,29.48,19.74,11.81,6.54,0.00,0.00,6.07,4.06
30,74.70,0.80,8.40,11.30,0.50,1.90,0.30,1.80,0.30
31,38.12,1.59,13.38,34.45,0.93,1.88,0.77,1.33,7.55
32,55.08,5.29,11.48,19.63,1.26,2.12,1.02,1.20,2.92
33,28.32,33.98,11.40,10.57,1.37,2.40,1.24,2.25,8.38
34,60.79,0.00,10.18,17.20,1.22,4.94,1.00,1.79,2.88